FROM python:3.12-alpine

RUN pip install poetry

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false && poetry install

COPY . .

CMD ["poetry", "run", "pytest", "tests/"]