version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '%(levelname)-8s %(name)s:%(funcName)s — %(message)s'

  development_format:
    format: '[%(levelname)s] %(filename)s:%(funcName)s:%(lineno)d — %(message)s'

filters:
  development_filter:
    (): app.core.log_filter.DevelopmentFilter

handlers:
  default:
    (): logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

  development_stdout_handler:
    (): logging.StreamHandler
    formatter: development_format
    filters: [ development_filter ]
    stream: ext://sys.stdout

loggers:
  development:
    level: DEBUG
    handlers: [ development_stdout_handler ]
    propagate: False

root:
  formatter: default
  handlers: [ default ]
